import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs labor
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories mirror the shape shared across warehouse-systems
 * documentation sites: Overview, Business Context, Domain-Driven Design,
 * API Reference, Ecosystem, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    'business-context/domain-vision',
    'ddd/subdomain-classification',
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/rest/labor-performance-api'},
      items: [...apiSidebar],
    },
    'ecosystem/context-map',
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-new-bounded-context-not-extension-of-workforce-or-fulfillment',
        'adr/0003-kafka-choreography-consumer-of-fulfillment-execution',
        'adr/0004-standard-frozen-at-completion-time-not-recomputed',
        'adr/0005-associate-trend-and-coaching-flag',
      ],
    },
  ],
};

export default sidebars;
